#!/bin/bash

echo 'Start processing'

time ruby process_file.rb tmp/100.txt
echo '------'
time ruby process_file.rb tmp/1k.txt
echo '------'
time ruby process_file.rb tmp/5k.txt
echo '------'
time ruby process_file.rb tmp/10k.txt
echo '------'
time ruby process_file.rb tmp/30k.txt
echo '------'
time ruby process_file.rb tmp/50k.txt
echo '------'
time ruby process_file.rb tmp/100k.txt
echo '------'
time ruby process_file.rb tmp/250k.txt
echo '------'
time ruby process_file.rb tmp/500k.txt
echo '------'
time ruby process_file.rb tmp/1m.txt
echo '------'
time ruby process_file.rb tmp/10m.txt
echo '------'
time ruby process_file.rb tmp/50m.txt
echo '------'
time ruby process_file.rb tmp/100m.txt

echo 'Stop processing'
